### PR TITLE
 Added Public IP, Subnet and Security group functionality in Openstack controller (oscm-app-openstack)

### PR DESCRIPTION
**Pull request by pujarisat**
We have added below functionality on openstack controller and also we have modified the classes as per the new functionality 

Requirements

1)  Add security group
2)  Add public IP
3)  Add subnet 

Modified and added new Files  

1)  PropertyHandler .java : added one constant variable named SECURITY_GROUPS and modify the getTemplateParameters () as per the new requirement 
2)  Created new technical service which is named as TechnicalServices_K5_PublicIP_SecurityGroup_Subnet.xml
3)  Created two new template 
a.  template_k5_new.json
b.  template_k5_new.yaml

Same has been tested on development environment and it’s working fine , attaching here Unit and integration test result document  .
Kindly check and let me know if any issue or concern .
[OSCM K5 Unit & Integration Testing.docx](https://github.com/servicecatalog/development/files/552502/OSCM.K5.Unit.Integration.Testing.docx)

---

This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/409)

### CODE REVIEW

**Comment by misako0927** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[oscm-app-openstack/resources/TechnicalServices_K5_PublicIP_SecurityGroup_Subnet.xml, line 1 at r2](https://reviewable.io:443/reviews/servicecatalog/development/409#-KV4VfBwKoAezpKr97Gc:-KV4VfBxtpOHMSzrylJ8:b-mfaz1c) ([raw file](https://github.com/servicecatalog/development/blob/5cecb60aa950b3a19f560a1dc3ad57dcb17d4800/oscm-app-openstack/resources/TechnicalServices_K5_PublicIP_SecurityGroup_Subnet.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Please unit this TechnicalService XML to old TechnicalService XML for K5.

---

*[oscm-app-openstack/resources/template_k5_new.json, line 1 at r2](https://reviewable.io:443/reviews/servicecatalog/development/409#-KV4W-cWVGFegeCLwFRk:-KV4W-cWVGFegeCLwFRl:b-4vulwx) ([raw file](https://github.com/servicecatalog/development/blob/5cecb60aa950b3a19f560a1dc3ad57dcb17d4800/oscm-app-openstack/resources/template_k5_new.json#L1)):*
> ```JSON
> {
> ```

JSON template is not supported by K5 so we don't have to prepare JSON template.

---

*[oscm-app-openstack/resources/template_k5_new.yaml, line 1 at r2](https://reviewable.io:443/reviews/servicecatalog/development/409#-KV4WGU53O53cKm3hINy:-KV4WGU53O53cKm3hINz:b-grm6my) ([raw file](https://github.com/servicecatalog/development/blob/5cecb60aa950b3a19f560a1dc3ad57dcb17d4800/oscm-app-openstack/resources/template_k5_new.yaml#L1)):*
> ```YAML
> heat_template_version: 2013-05-23
> ```

Please unit this yaml template to old yaml template for K5.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Comment by StavrevaS** [comment]
Reviewed 9 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java, line 231 at r2](https://reviewable.io:443/reviews/servicecatalog/development/409#-KVP5RJ2nSsU9-lF3IBk:-KVP5RJ2nSsU9-lF3IBl:b-p23zfv) ([raw file](https://github.com/servicecatalog/development/blob/5cecb60aa950b3a19f560a1dc3ad57dcb17d4800/oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java#L231)):*
> ```Java
> 
>         case CREATING:
>             LOGGER.info("trying to check sataus");
> ```

Correct spelling

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java, line 229 at r2](https://reviewable.io:443/reviews/servicecatalog/development/409#-KVPALkhTL4GuVF9WZ4-:-KVPALkiOX935R8vnXlT:b-3uo40f) ([raw file](https://github.com/servicecatalog/development/blob/5cecb60aa950b3a19f560a1dc3ad57dcb17d4800/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java#L229)):*
> ```Java
>         // created security Group array , user can add security group separated
>         // by comma
>         JSONArray securityGroupSecurityGroup = new JSONArray();
> ```

Did you test the code with more security groups?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Comment by StavrevaS** [comment]
Please add unit tests for the changed methods.

**Comment by GoebelL** [comment]
Hi @pujarisat, 
do you have an update here?

**Comment by pujarisat** [comment]
Hi Team,

We have modified the code and file as per the team suggestion and same has been committed . kindly check and let me know if any changes 

Changes : 
-	Added test cases for check the modified code 
-	Modify the technical service and yaml template as per the requirement 

Thanks 
Satling

**Comment by StavrevaS** [comment]
Reviewed 4 of 6 files at r3.
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Comment by StavrevaS** [comment]
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java, line 238 at r3](https://reviewable.io:443/reviews/servicecatalog/development/409#-KW7-MYhneYB-i4lmvOk:-KW7-MYiVl2mXH0wmxiH:bknrrsz) ([raw file](https://github.com/servicecatalog/development/blob/d3dfe2e66147dd688ca4d3f473b6abb9b93480e6/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java#L238)):*
> ```Java
>                             settings.getParameters().get(key));
>                 }
>             }
> ```

The logic for security group parameters should be unified with the logic for other template parameters (prefix "TP_"). The comma separated values should be put as json array in the parameter map (as it is implemented for security groups now). The identifier of security group parameter is here hard-coded, but it depends on the template. This should be changed like for other parameters, the technology manager should specify the identifier in the technical service to match the identifier from the template.
Please adapt the junit tests if necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Comment by StavrevaS** [comment]
Reviewed 1 of 6 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Comment by misako0927** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[oscm-app-openstack/resources/TechnicalService_K5.xml, line 163 at r4](https://reviewable.io:443/reviews/servicecatalog/development/409#-KWDDidIqw0EDyE0gctd:-KWDDidIqw0EDyE0gcte:b-2mggoc) ([raw file](https://github.com/servicecatalog/development/blob/1ac335fc51d51cadaa37bbc50a39dc332473c7ec/oscm-app-openstack/resources/TechnicalService_K5.xml#L163)):*
> ```XML
>     </ParameterDefinition>
> 	<ParameterDefinition configurable="true" id="TP_VmName" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
>       <LocalizedDescription locale="en">VmName</LocalizedDescription>
> ```

LocalisedDescription is description of parameter. Please don't write like variable but write like description(ex. not VmName but VM name)

---

*[oscm-app-openstack/resources/template_k5.yaml, line 9 at r4](https://reviewable.io:443/reviews/servicecatalog/development/409#-KWDCTz4602KGimwcvXf:-KWDCTz4602KGimwcvXg:b6fcyz7) ([raw file](https://github.com/servicecatalog/development/blob/1ac335fc51d51cadaa37bbc50a39dc332473c7ec/oscm-app-openstack/resources/template_k5.yaml#L9)):*
> ```YAML
>     description: The id of the image to provision.
>     type: string
>     default: <please input your image id>
> ```

Please unify whether to set default in all parameters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/409)*

**Pull request merged**
