### PR TITLE
pull request for #241

### PR DESCRIPTION
**Pull request by misako0927**
This is pull request for #241 .
Please review these feature:
  * add route to use keystone API v3
      * add parameter of domain ID and tenant ID
      * Using TLS v1.2 protocols to connect K5
  * fix checking server exist logic in order not only to use server name "Server"

Unfortunately I could not prepare message for German. If somebody can write in German, please translate..

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/263)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 154 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJueuVq2UY00wm9vK-:-KOJueuWyao5cDwoSDDy:1776049150) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L154)):*
> ```Java
>             for (int i = 0; i < resources.length(); i++) {
>                 JSONObject resource = resources.getJSONObject(i);
>                 if ("OS::Nova::Server".equalsIgnoreCase(resource.optString("resource_type"))
> ```

Extract enumeration and use in tests also.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java, line 216 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJm4GCO1Bx-DQHO_x6:-KOJm4GDSelpVNDsCRXO:887400075) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java#L216)):*
> ```Java
>                 	// This setting is only needed for K5.
>                 	// We have to support multi protocols.
>                 	SSLContext sslcontext = SSLContext.getInstance("TLSv1.2");
> ```

If this setting is working, the protocol should be a part of controller configuration. Since always https is used, this must be corrected to be configurable if really needed.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 168 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJrdd3Anzjje3zXQDc:-KOJrdd44cSXegZBXpJo:861684352) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L168)):*
> ```Java
>         String uri = connection.getKeystoneEndpoint() + "/tokens";
> 
>         JSONObject request = new JSONObject();
> ```

This method should be refactored, together with the existing one for V2 authentication. There is a lot of code duplication, including constants. Also deep nesting levels.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/OpenStackConnection.java, line 280 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJo1X_6FA8TCkUXsHf:-KOJo1X_6FA8TCkUXsHg:887400075) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/OpenStackConnection.java#L280)):*
> ```Java
>             	// This setting is only needed for K5.
>             	// We have to support multi protocols.
>                 SSLContext sslcontext = SSLContext.getInstance("TLSv1.2");
> ```

If this setting is working, the protocol should be a part of controller configuration. Since always https is used, this must be corrected to be configurable if really needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by misako0927** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 154 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJueuVq2UY00wm9vK-:-KQy4U2i19hHNJ76ohV5:b6r7hkt) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L154)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Extract enumeration and use in tests also.
</details>
Excuse me, do you mean I have to add more test about this code?
I cannot understand "extract enumeration" mean.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java, line 216 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJm4GCO1Bx-DQHO_x6:-KQxhh8SZPVeDyzcf_-W:b-7k65bt) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java#L216)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> If this setting is working, the protocol should be a part of controller configuration. Since always https is used, this must be corrected to be configurable if really needed.
</details>
I'm sorry I forgot fix this. I would like to discuss about this. The reason that I wrote this code is  I got error from connecting WSDL when I set this in controller configuration. I think this code only need for K5. (Those settings depend on cloud environment.)
On the other hand, we will upgrade glassfish and glassfish 4 support TSLv1.2. At that time, we may not need this code.
I could not decide I should remove this code or not. Do you have any idea?

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 168 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJrdd3Anzjje3zXQDc:-KQy1vwiSqC5a73AzLqD:ba4i0q5) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L168)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> This method should be refactored, together with the existing one for V2 authentication. There is a lot of code duplication, including constants. Also deep nesting levels.
</details>
I also thought I can convert v2 and v3. But if I do so, I think we need many if part in that method. I think it is not good for 
maintainability. If you have any good idea, please let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by StavrevaS** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 154 at r1](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJueuVq2UY00wm9vK-:-KRST-GleumAkJit0VlV:bnp97fb) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L154)):*
<details><summary><i>Previously, misako0927 (misako tateiwa) wrote…</i></summary>
> Excuse me, do you mean I have to add more test about this code?
> I cannot understand "extract enumeration" mean.
</details>
There are some constant values like "OS::Nova::Server", which are used in tests also. It is better to have it as enumeration which can be used from tests also. That is what I meant with "Extract enumeration". On the other hand, if you have constant values which are repeated only in this class, you can define them as private static and final fields of the class. We should avoid repeating the same constant values in the code.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 168 at r1](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJrdd3Anzjje3zXQDc:-KRSU6tG_YD_uU2FKUvh:b3kbsee) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L168)):*
<details><summary><i>Previously, misako0927 (misako tateiwa) wrote…</i></summary>
> I also thought I can convert v2 and v3. But if I do so, I think we need many if part in that method. I think it is not good for 
> maintainability. If you have any good idea, please let me know.
</details>
The duplicate code can be extract in separate methods, used by v2 and v3 methods. About many nesting levels, maybe you can add boolean methods with meaningful names which describe the condition tested. For example condition methods isHeatType(), isNovaType, isPublicUrl() etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by StavrevaS** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java, line 216 at r1](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJm4GCO1Bx-DQHO_x6:-KRS_kkIFwE9tc0Szw6m:b-fqmnub) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java#L216)):*
<details><summary><i>Previously, misako0927 (misako tateiwa) wrote…</i></summary>
> I'm sorry I forgot fix this. I would like to discuss about this. The reason that I wrote this code is  I got error from connecting WSDL when I set this in controller configuration. I think this code only need for K5. (Those settings depend on cloud environment.)
> On the other hand, we will upgrade glassfish and glassfish 4 support TSLv1.2. At that time, we may not need this code.
> I could not decide I should remove this code or not. Do you have any idea?
</details>
The following maybe a intermediate solution: define protocol in ProxySettings.java like all other proxy constants. Now you can define the protocol as JVM property in Glassfish. The Glassfish will probably ignore it, but the OpenStack code can read it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by misako0927** [comment]
Review status: 7 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 154 at r1](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJueuVq2UY00wm9vK-:-KS1eDJawTOrFXvLe_ut:biui99o) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L154)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> There are some constant values like "OS::Nova::Server", which are used in tests also. It is better to have it as enumeration which can be used from tests also. That is what I meant with "Extract enumeration". On the other hand, if you have constant values which are repeated only in this class, you can define them as private static and final fields of the class. We should avoid repeating the same constant values in the code.
</details>
I changed the code to use enumeration. Please check it.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 168 at r1](https://reviewable.io:443/reviews/servicecatalog/development/263#-KOJrdd3Anzjje3zXQDc:-KS1eZLwJf568c7Tc26a:bj792rz) ([raw file](https://github.com/servicecatalog/development/blob/d4e953f1182578de673bda2076eb401458d63c79/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L168)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> The duplicate code can be extract in separate methods, used by v2 and v3 methods. About many nesting levels, maybe you can add boolean methods with meaningful names which describe the condition tested. For example condition methods isHeatType(), isNovaType, isPublicUrl() etc.
</details>
I talked with Lorenz and I removed keystone API v2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by StavrevaS** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Comment by StavrevaS** [comment]
Reviewed 3 of 5 files at r3.
Review status: 18 of 20 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/263)*

**Pull request merged**
