### PR TITLE
Added function to sort drop down menus in place using Javascript.

### PR DESCRIPTION
**Pull request by angarg12**
#304 
Added a new function to admUtils to sort drop down menus.
Modified main.xhtml so that this function is triggered site wide.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/312)

### CODE REVIEW

**Comment by DawidCh** [comment]
Hello.
You have modified more than 2000 lines of code. This is because formatter you have applied on both files. Could you please apply proper formatting before the merge, to see what has been modified?
Regards, Dawid.

**Comment by angarg12** [comment]
Could you please provide me with the formatter that I need to apply?

**Comment by angarg12** [comment]
The problem was with line endings. Although I have Eclipse configured to use Unix line endings, it was saving the files with windows ones.

**Comment by DawidCh** [comment]
Your changes are not visible. Create new branch from our master apply your changes and create new pull request, please.

**Pull request closed without merging**
