### PR TITLE
Improvements from and for OSCMaaS

### PR DESCRIPTION
**Pull request by MiethanerR**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/600)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[oscm-accountmgmt-unittests/javasrc-it/org/oscm/accountservice/bean/AccountServiceBeanIT.java, line 2212 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu8OAOJmJULPQvqxP-:-Kfu8OAPJt6VFQOEzf9I:bz8re1e) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-accountmgmt-unittests/javasrc-it/org/oscm/accountservice/bean/AccountServiceBeanIT.java#L2212)):*
> ```Java
>                 l_organization = accountMgmtLocal.registerOrganization(
>                         l_organization, null, userDetails, null, "DE",
>                         marketplaceId, null, OrganizationRoleType.SUPPLIER);
> ```

Almost  all tests have now marketplaceId as parameter.  Does this mean the service is only tested for marketplace? Register organization is called also without marketplace context.

---

*[oscm-accountmgmt/javasrc/org/oscm/accountservice/bean/AccountServiceBean.java, line 1447 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-KfuFUyJHj6_obCqkN9e:-KfuFUyK_2VqoXhiUEwW:b5pjpap) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-accountmgmt/javasrc/org/oscm/accountservice/bean/AccountServiceBean.java#L1447)):*
> ```Java
>         VOOrganization result = null;
>         Marketplace mp = new Marketplace(marketplaceId);
>         mp = (Marketplace) dm.getReferenceByBusinessKey(mp);
> ```

How the default tenant fits in this logic? The tenant key of the VOOrganization will be overwritten.

---

*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2723 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu7CKqTw1jVO9RrAcZ:-Kfu7CKqTw1jVO9RrAc_:bn2zu27) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2723)):*
> ```Java
>         // TODO DEL
>         Tenant tenant = null;
>         try {
> ```

The logic with the tenant from marketplace is removed here. Creating user is also possible from marketplace portal. Is this tested with different tenants?

---

*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2730 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu6R58vR1yD6n9dSsc:-Kfu6EJ2VdUdf61JtWRR:b-h5eifz) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2730)):*
> ignore
It is better to write a log warning here, instead of ignoring. This is the case is the tenant is not known to the system. It should not happen, but it would be easier for analyzing if problem occurs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/600)*

**Comment by StavrevaS** [comment]
@MiethanerR please provide the build numbers with which this issue is tested.

**Comment by MiethanerR** [comment]
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[oscm-accountmgmt/javasrc/org/oscm/accountservice/bean/AccountServiceBean.java, line 1447 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-KfuFUyJHj6_obCqkN9e:-KgONTLePpmJ33Pv9AZZ:bxh6sve) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-accountmgmt/javasrc/org/oscm/accountservice/bean/AccountServiceBean.java#L1447)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

How the default tenant fits in this logic? The tenant key of the VOOrganization will be overwritten.
</blockquote></details>

A marketplace within the default tenant has a null value as tenant reference. The 0 tenant key value in the organization is also an indicator for the default tenant.

---

*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2723 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu7CKqTw1jVO9RrAcZ:-KgOLxCJKK3FshOH7Ghx:bjwfp97) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2723)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

The logic with the tenant from marketplace is removed here. Creating user is also possible from marketplace portal. Is this tested with different tenants?
</blockquote></details>

Yes, the marketplace logic was not reachable so I removed it.

---

*[oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java, line 2730 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu6R58vR1yD6n9dSsc:-KgOM8nuQqBlKYB8J5Sv:b-hea592) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-identitymgmt/javasrc/org/oscm/identityservice/bean/IdentityServiceBean.java#L2730)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

> ignore
It is better to write a log warning here, instead of ignoring. This is the case is the tenant is not known to the system. It should not happen, but it would be easier for analyzing if problem occurs.

</blockquote></details>

For the default tenant it is expected that a exception is thrown, so a warning would be only confusing in my opinion.

---

*[oscm-accountmgmt-unittests/javasrc-it/org/oscm/accountservice/bean/AccountServiceBeanIT.java, line 2212 at r2](https://reviewable.io:443/reviews/servicecatalog/development/600#-Kfu8OAOJmJULPQvqxP-:-KgOMXt-qRNFeAu8-ZyR:b-sjxohj) ([raw file](https://github.com/servicecatalog/development/blob/61105c10eb06f783e0b5ece334b68891c6f849fb/oscm-accountmgmt-unittests/javasrc-it/org/oscm/accountservice/bean/AccountServiceBeanIT.java#L2212)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

Almost  all tests have now marketplaceId as parameter.  Does this mean the service is only tested for marketplace? Register organization is called also without marketplace context.
</blockquote></details>

I reverted these changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/600)*

**Comment by MiethanerR** [comment]
Build: OSCMaaS-Delivery #6

**Pull request merged**
