### PR TITLE
Openstack extension

### PR DESCRIPTION
**Pull request by skulle**
Provision Openstack projects, collect usage information

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/857)

### CODE REVIEW

**Comment by GoebelL** [comment]
Hi @skulle 

First of all, great extensions for the OpenStack adapter, having provision capabilities for OpenStack projects and gathering usage data!

My comments from first review

1. Main changes for project related part seem to be 
```
oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/OpenStackController.java
oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java
oscm-app-openstack/javasrc/org/oscm/app/openstack/data/FlowState.java 
```
From my first sight this implementation is ok.

2. For the usage part
 ```
oscm-app-openstack/javasrc/org/oscm/app/openstack/usage/EventTimer.java
 oscm-app-openstack/javasrc/org/oscm/app/openstack/usage/UsageConverter.java
 oscm-app-openstack/javasrc/org/oscm/app/openstack/OpenstackClient.java
```
Encryption and credentials handling need to be cleared. From my gut feeling this is redundant.
Technology provider credentials can be retrieved from controller settings. 
See` APPlatformService#getControllerSettings`.
**Constraints**: No database accesses and authentication logic in this layer

TBD: Refactoring
- Replace AppDb and loadTechnologyProviderCredentials() to use API (Auth direction to BES)
- Consolidate to use existing custom attributes from ProvisioningSettings passed with the provisioning service (Auth direction to Cloud)

Others
1. Added 3rd party
   - openstack4j-httpclient-3.1.0.jar 
   - openstack4j-core-3.1.0.jar
These libraries can be found in central maven. All licenses are ok with OSCM. 
TBD: Remove binaries from PR and add respective dependencies in OSCM ivy build. 

2. PostgreSQL JDBC client
Currently we use postgresql-9.4-1206-jdbc42.jar. Older version in APP will be dropped. You are introducing postgresql-42.1.4.jar. 
TBD: Use postgresql-9.4-1206-jdbc42.jar if possible. 

3. Changes is oscm-build/ 
Are all of them included by intention?
ANT build and test targets already exist quite many. Of course, improvements are always welcome. Let's address this for later.

**Comment by DawidCh** [comment]
Hi.
Thanks for contribution but the travis build fails. Could you please fix it?
Regards, Dawid.

**Comment by DawidCh** [comment]
Cool, thanks.

**Comment by DawidCh** [comment]
Please report pull request in to new repository:
https://github.com/servicecatalog/oscm/tree/openstack_extension

**Pull request closed without merging**
