### PR TITLE
APP template upload

### PR DESCRIPTION
**Pull request by MiethanerR**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/678)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oscm-app/resources/sql/upd_postgresql_02_06_08.sql, line 6 at r1](https://reviewable.io:443/reviews/servicecatalog/development/678#-KhVeEpKFuWNoW_lCsrO:-KhVeEpKFuWNoW_lCsrP:bpzpusr) ([raw file](https://github.com/servicecatalog/development/blob/070a027b814fe4f83a92eabe32deb13eafc366f2/oscm-app/resources/sql/upd_postgresql_02_06_08.sql#L6)):*
> ```SQLPL
>   "filename" character varying(255) NOT NULL,
>   "content" OID NOT NULL,
>   "lastchange" timestamp with time zone NOT NULL,
> ```

OSCM uses timestamps without time zone in the database. The UI should show the UTC time zone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/678)*

**Comment by StavrevaS** [comment]
How the technical services references the templates? As I can see both ways with URL and db are supported in the controller. But I cannot find any technical service sample changed.

**Comment by MiethanerR** [comment]
The base URL is configured in the controller settings, the tech. service contains only the name of the template, so I didn't need to change there anything.

**Comment by MiethanerR** [comment]
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[oscm-app/resources/sql/upd_postgresql_02_06_08.sql, line 6 at r1](https://reviewable.io:443/reviews/servicecatalog/development/678#-KhVeEpKFuWNoW_lCsrO:-KhaVwvY-dJqt_UQD2hv:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/070a027b814fe4f83a92eabe32deb13eafc366f2/oscm-app/resources/sql/upd_postgresql_02_06_08.sql#L6)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

OSCM uses timestamps without time zone in the database. The UI should show the UTC time zone.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/678)*

**Pull request merged**
