### PR TITLE
pull request for #241

### PR DESCRIPTION
**Pull request by misako0927**
Change KEYSTONE_API_URL sample in configsettings_controller.properties

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/331)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 187 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHJKhqKJkfnFIXOWdv:-KSHJKhrrx1q2Da-I2Tl:b14t8zp) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L187)):*
> ```Java
>                 }
>                 switch (type) {
>                 case NOVA:
> ```

How can a resource have a resource_type null? Is this not mandatory?

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 88 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHIydt5dwnhuOCdwQO:-KSHIydt5dwnhuOCdwQP:bmc2igu) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L88)):*
> ```Java
>             throw new RuntimeException(e);
>         }
>         RESTResponse response = connection.processRequest(uri, "POST",
> ```

Please do not remove the debug statements. We must find a way to hide the password in the log.  

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java, line 196 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHHoXn2pJW1oDCILGp:-KSHHoXn2pJW1oDCILGq:b-3i50fg) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java#L196)):*
> ```Java
>         if (domain == null || domain.trim().length() == 0) {
>             domain = settings.getConfigSettings().get(DOMAIN_NAME);
>             if (domain == null) {
> ```

Empty string should be tested also, not only null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/331)*

**Comment by misako0927** [comment]
*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 187 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHJKhqKJkfnFIXOWdv:-KSHN39JjhY0Otn4z4Tt:b-wx0bl9) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L187)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> How can a resource have a resource_type null? Is this not mandatory?
</details>
I only set Nova, Trove, and EC2 in this code and getInstanceType return null if other resource (ex. "OS::Cinder::Volume") is argument.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/331)*

**Comment by misako0927** [comment]
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java, line 88 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHIydt5dwnhuOCdwQO:-KSHVxLqLFNSvCfhvWmL:b5kbzj7) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/KeystoneClient.java#L88)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Please do not remove the debug statements. We must find a way to hide the password in the log.  
</details>
I added debug log and hide password.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java, line 196 at r2](https://reviewable.io:443/reviews/servicecatalog/development/331#-KSHHoXn2pJW1oDCILGp:-KSHW1aE2BXdK3-TOkDX:b8vsw2t) ([raw file](https://github.com/servicecatalog/development/blob/1b0910c51d7c3164714daa8078558a234e9ed68a/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/PropertyHandler.java#L196)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Empty string should be tested also, not only null?
</details>
I added empty string implementation and test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/331)*

**Comment by StavrevaS** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/331)*

**Pull request merged**
