### PR TITLE
Start and stop instances operation #311

### PR DESCRIPTION
**Pull request by misako0927**
Add start and stop operation to each VMs at once. #311
I added message to messages_xx.properties but I could not write in German so I just add in English in messages_de.properties.
Please someone fix this issue.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/348)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java, line 12 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ6yggqxZN56wk942m:-KTJ6yggqxZN56wk942n:b5huc02) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java#L12)):*
> ```Java
> 
> import static org.junit.Assert.assertEquals;
> import static org.junit.Assert.assertFalse;
> ```

Please keep the resume stack and suspend stack functionality. It should not be deleted, even we have new operation using Nova API.

---

*[oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties, line 31 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBT5QcMzCDFkfMTI5:-KTJBT5QcMzCDFkfMTI6:b3lv9x3) ([raw file](https://github.com/servicecatalog/development/blob/4a69cefc225531341441157cd2474f435041941d/oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties#L31)):*
> ```INI
> error_update_failed_customer=The update of the requested resources failed. The service provider has been informed about the issue.
> error_update_failed_provider=Stack update failed with status reason {0}
> error_activating_failed=The activation of the requested resources failed with status reason {0}
> ```

Why this is deleted?

---

*[oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties, line 37 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBB46qHfrQ4TuZPtL:-KTJBB46qHfrQ4TuZPtM:b5r2ern) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties#L37)):*
> ```INI
> error_deleting_stack_failed=The deletion of the requested resources failed with status reason {0}
> error_heat_resource_not_found=Requested Heat resource not found: {0}.
> error_check_servers_status_failed_instance_not_found=The getting status failed because instances in stack {0} no longer exists, while the subscription is still available to the customer.
> ```

We should not mention that subscription is available to the customer. The subscriptions are controlled by OSCM, not controller.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 10 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJB_owjbGjT8IMbceK:-KTJB_oxQT4Ltpt0hFpM:b1v5q0v) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L10)):*
> ```Java
> 
> package org.oscm.app.openstack;
> ```

Resume and suspend stack should not be deleted.  

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java, line 110 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBiCMgdrLpCS_f5jY:-KTJBiCMgdrLpCS_f5jZ:b2hsafk) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java#L110)):*
> ```Java
>         return new HeatClient(connection);
>     }
> ```

We need separate NovaProcessor class.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/NovaClient.java, line 8 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJCgNg-Fq5m3MWgNjs:-KTJCgNg-Fq5m3MWgNjt:b-2tczgm) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/NovaClient.java#L8)):*
> ```Java
>  *                                                                              
>  *******************************************************************************/
> ```

Please, solve the TODOs

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/Dispatcher.java, line 132 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ8S6QEHKO_OSwCSwm:-KTJ8S6QEHKO_OSwCSwn:bkipxkv) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/Dispatcher.java#L132)):*
> ```Java
>                 break;
> 
>             case ACTIVATION_REQUESTED:
> ```

This is provisioning action and in my opinion, we should stay to the resume stack action. The stack may contain more resources, not only VMs, so I am not sure if only starting all VMs is enough. 

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/HeatStatus.java, line 15 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ8-wEV93tj8fmcHIN:-KTJ8-wEV93tj8fmcHIO:b-uvfhij) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/HeatStatus.java#L15)):*
> ```Java
>  * 
>  */
> public enum HeatStatus {
> ```

Rename to StackStatus, because the enumeration describes the stack status.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/348)*

**Comment by misako0927** [comment]
Review status: 12 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java, line 12 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ6yggqxZN56wk942m:-KTKTltzj7-PD-3wCehl:beldq1q) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java#L12)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Please keep the resume stack and suspend stack functionality. It should not be deleted, even we have new operation using Nova API.
</details>
I'll revert resume function. 

---

*[oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties, line 31 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBT5QcMzCDFkfMTI5:-KTKVJphvThtz7jtlZpx:b-j4q34d) ([raw file](https://github.com/servicecatalog/development/blob/4a69cefc225531341441157cd2474f435041941d/oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties#L31)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Why this is deleted?
</details>
I deleted stack status reason because we could not get any reason from stack when we execute start operation to each VMs.
I'll revert this message in order to revert resume stack function.

---

*[oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties, line 37 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBB46qHfrQ4TuZPtL:-KTKWLjM3PjLnj7AFAN5:belyf66) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javares/org/oscm/app/openstack/i18n/messages_en.properties#L37)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> We should not mention that subscription is available to the customer. The subscriptions are controlled by OSCM, not controller.
</details>
I could not understand what do you mean. This message will be shown when operation is failed. The operation is failed but OSCM not sure stack and VMs are still alive or not. I think that's why this message is written. Other operation also use same message. If it is not good, we should change all message for other operations.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java, line 10 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJB_owjbGjT8IMbceK:-KTKZ-FdA5FHxsNoLHAk:beldq1q) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatClient.java#L10)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Resume and suspend stack should not be deleted.  
</details>
I'll revert resume function. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/348)*

**Comment by misako0927** [comment]
TechnicalService_OpenStack.xml also have message in German but I couldn't write in German.. Please fix it...

**Comment by misako0927** [comment]
Review status: 1 of 41 files reviewed at latest revision, 8 unresolved discussions.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java, line 110 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJBiCMgdrLpCS_f5jY:-KTtKba0ZuvE70NMgkGl:bn5q1g3) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/HeatProcessor.java#L110)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> We need separate NovaProcessor class.
</details>
I fixed code to use NovaProcessor

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/NovaClient.java, line 8 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJCgNg-Fq5m3MWgNjs:-KTtKk75uGmDok19Ev7S:b56dvjr) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/NovaClient.java#L8)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Please, solve the TODOs
</details>
I resolved it.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/Dispatcher.java, line 132 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ8S6QEHKO_OSwCSwm:-KTtKm-b5J-LHjuoe-h3:b-na0vue) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/Dispatcher.java#L132)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> This is provisioning action and in my opinion, we should stay to the resume stack action. The stack may contain more resources, not only VMs, so I am not sure if only starting all VMs is enough. 
</details>
I changed flow. I revert resume stack action.

---

*[oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/StackStatus.java, line 15 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ8-wEV93tj8fmcHIN:-KTtL1Rk4NLkCzZtUD4I:b-1z2jjy) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack/javasrc/org/oscm/app/openstack/controller/StackStatus.java#L15)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Rename to StackStatus, because the enumeration describes the stack status.
</details>
I changed the name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/348)*

**Comment by GoebelL** [comment]
Review status: 1 of 41 files reviewed at latest revision, 8 unresolved discussions.

---

*[oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java, line 12 at r2](https://reviewable.io:443/reviews/servicecatalog/development/348#-KTJ6yggqxZN56wk942m:-KTtMU6Z1VZ92dUneo44:b2nhll9) ([raw file](https://github.com/servicecatalog/development/blob/48eb570a4f1f76e235b9b8e9bfcb1138b3c91178/oscm-app-openstack-unittests/javasrc/org/oscm/app/openstack/HeatProcessorTest.java#L12)):*
<details><summary><i>Previously, misako0927 (misako tateiwa) wrote…</i></summary>
> I'll revert resume function. 
</details>
Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/348)*

**Comment by GoebelL** [comment]
Reviewed 2 of 15 files at r2, 12 of 19 files at r3, 22 of 29 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/348)*

**Pull request merged**
