### PR TITLE
Fb multitenancy ws api

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/363)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 31 of 31 files at r1.
Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[oscm-installation/install/patch-SSO.xml, line 84 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGnzvuPykHMYdXlFPz:-KUGnzvuPykHMYdXlFQ-:b-bewtwf) ([raw file](https://github.com/servicecatalog/development/blob/6b16c669c281f466e2966748e498147530ecff35/oscm-installation/install/patch-SSO.xml#L84)):*
> ```XML
>             <filter token="SSO_STS_METADATA_URL" value="${SSO_STS_METADATA_URL}" />
>           </filterset>
>         </copy>
> ```

Can we delete here more than filterset?

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java, line 98 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrDPfSBkQDoMcRXzR:-KUGrDPfSBkQDoMcRXzS:bo7em9o) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java#L98)):*
> ```Java
>         String value = (String) query.getSingleResult();
>         return value;
>     }
> ```

Why native query here? It is not performance critical.

---

*[oscm-webservices/javasrc/org/oscm/webservices/handler/UserKeyQuery.java, line 30 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrXt2Yf6atf_eZ1Fp:-KUGrXt2Yf6atf_eZ1Fq:b-ae4vnr) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-webservices/javasrc/org/oscm/webservices/handler/UserKeyQuery.java#L30)):*
> ```Java
>         return "SELECT pu.tkey FROM PlatformUser pu JOIN organization o on pu.organizationkey=o.tkey where o.tenant_tkey is null and pu.userid=?";
>     }
> ```

Does this query search for user in default tenant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363)*

**Comment by StavrevaS** [comment]
Hello @kowalczyka, it seems fine to me. I have some comments, please answer or fix. Please make a detailed review in your team.

**Comment by kowalczyka** [comment]
Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oscm-installation/install/patch-SSO.xml, line 84 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGnzvuPykHMYdXlFPz:-KUH47ud2pVUDlgC36uu:b-nfth65) ([raw file](https://github.com/servicecatalog/development/blob/6b16c669c281f466e2966748e498147530ecff35/oscm-installation/install/patch-SSO.xml#L84)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Can we delete here more than filterset?
</details>
Not really. We must leave copying of wsit and webservices config files - as without this we have no STS related webservices definitions. I only removed ther proccess of patching the STS configuration settings. To delete this part we would have to change the default configuration. Do you think we should proceedd in this direction?

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java, line 98 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrDPfSBkQDoMcRXzR:-KUH736nIK-a_EznH2sQ:b-yip8pp) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java#L98)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Why native query here? It is not performance critical.
</details>
Should I prepare the named query instead?

---

*[oscm-webservices/javasrc/org/oscm/webservices/handler/UserKeyQuery.java, line 30 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrXt2Yf6atf_eZ1Fp:-KUH3Mw_m2Q2BoNY7K28:b7wnk35) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-webservices/javasrc/org/oscm/webservices/handler/UserKeyQuery.java#L30)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Does this query search for user in default tenant?
</details>
Yes.  It search users in default tenant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363)*

**Comment by kowalczyka** [comment]
@stavrevas  could you please comment my answers and questiona so that we could  proceed with this issue?

---

Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363#-:-KUROtge6TkwM_Ekas_d:b-4e46bm)*

**Comment by StavrevaS** [comment]
Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[oscm-installation/install/patch-SSO.xml, line 84 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGnzvuPykHMYdXlFPz:-KUWD3MQDZTQVjARtUHt:bgtgkjc) ([raw file](https://github.com/servicecatalog/development/blob/6b16c669c281f466e2966748e498147530ecff35/oscm-installation/install/patch-SSO.xml#L84)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary>
> Not really. We must leave copying of wsit and webservices config files - as without this we have no STS related webservices definitions. I only removed ther proccess of patching the STS configuration settings. To delete this part we would have to change the default configuration. Do you think we should proceedd in this direction?
</details>
It is OK, no changes here.

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java, line 98 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrDPfSBkQDoMcRXzR:-KUWCIRZzqApQZ2bh2z0:b-mgy2zl) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java#L98)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary>
> Should I prepare the named query instead?
</details>
Yes. We should avoid native if no reason for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363)*

**Comment by kowalczyka** [comment]
Review status: 16 of 53 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java, line 98 at r1](https://reviewable.io:443/reviews/servicecatalog/development/363#-KUGrDPfSBkQDoMcRXzR:-KWgSN1XEXNJCkvzqX7N:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/ca373186cfd3ec19c7847520159268b607af9e86/oscm-tenantmgmt/javasrc/org/oscm/tenant/dao/TenantDao.java#L98)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Yes. We should avoid native if no reason for that.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363)*

**Comment by kowalczyka** [comment]
Reviewed 19 of 31 files at r1, 1 of 2 files at r2, 21 of 26 files at r3, 1 of 1 files at r4, 14 of 14 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/363)*

**Pull request merged**
