### PR TITLE
Fix for null parameters

### PR DESCRIPTION
**Pull request by grubskim**
Null parameter values are changed to an empty string. Tested with the sample controller.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/895)

### CODE REVIEW

**Comment by StavrevaS** [comment]
It would be even more secure to add null to empty string transformation into the InstanceParameter.setParameterValue().
The method InstanceParameter.setDecryptedValue() may also set the value, so BEFORE the encryption it should be checked if the value is null and transform it.  So in this case the empty string should be encrypted in order to have the same result by decryption.

**Comment by grubskim** [comment]
Unit tests green, added @StavrevaS suggestion

**Comment by grubskim** [comment]
Please review and merge if okay.

**Comment by StavrevaS** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/895)*

**Comment by GoebelL** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/895#-:-L3bIMGeEvut1iCMBJ1m:bnfp4nl)*

**Pull request merged**
