### PR TITLE
Fixes #700 - 'APP Platform Settings' to just 'APP settings'

### LINKED ISSUE #700: APP UI: APP Platform Settings should read "APP Settings"
[Version]
17.0 2017/05/15 (bugfix branch, including issue #677)

[How to reproduce]
1.   go to http://estsdehn.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
The title of the section for updating the APP cfg settings is "APP Settings"

[Observed result]
The title is "APP Platform Settings"

[Details]
Since APP is the abbreviation for Asynchronous Provisioning Platform, the "Platform" in the title is superfluous.

### PR DESCRIPTION
**Pull request by digitalfishpond**
fixes #700

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/743)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
@gertipoppel PTAL

**Comment by gertipoppel** [comment]
OK for me. I don't have permissions to merge though

**Comment by digitalfishpond** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/743)*

**Comment by DawidCh** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/743)*

**Comment by digitalfishpond** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/743)*

**Pull request merged**
