### PR TITLE
Added tenant setting access during authentication process

### PR DESCRIPTION
**Pull request by grubskim**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/797)

### CODE REVIEW

**Comment by DawidCh** [comment]
Consider changes according the comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantConfigurationService.java, line 18 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozWES3GCLb4RmpShZ9:-KozWES3GCLb4RmpShZA:bwy4e9z) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantConfigurationService.java#L18)):*
> ```Java
>  */
> @Remote
> public interface TenantConfigurationService {
> ```

Is the remote access really needed? I think Local interface is sufficient. We will not call the bean from webservices or other distributed ears.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 61 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozWyvfhdA0XN3n0sx1:-KozWyvgEEkFMokkvofU:b-hh4nx3) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L61)):*
> ```Java
>             try {
>                 TenantConfigurationService tcb = getTenantConfigService();
>                 method = tcb.getHttpMethodForTenant(request.getParameter(Constants.REQ_PARAM_TENANT_ID));
> ```

The authenticationHandler is being called with every request (probably). If true consider moving result of ejb calls to session if possible.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 112 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozXKn-fN22Wr9omffX:-KozXKn0RQ1XrMSZvrpA:b-ghqela) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L112)):*
> ```Java
>         if (tenantID != null) {
>             issuer = getTenantConfigService().getIssuerForTenant(tenantID);
>             url = getTenantConfigService().getIdpUrlForTenant(tenantID);
> ```

Two ejb calls one by one which reaches for tenant specific data. May the both data be returned in the same time during one call? Small kittens are crying somewhere when performance is getting hit;)

---

*[oscm-tenantmgmt-intsvc/javasrc/org/oscm/tenant/local/TenantConfigurationServiceLocal.java, line 17 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozW_xc6Yz0YG75LgPE:-KozW_xc6Yz0YG75LgPF:bfgzx8q) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-tenantmgmt-intsvc/javasrc/org/oscm/tenant/local/TenantConfigurationServiceLocal.java#L17)):*
> ```Java
>  */
> @Local
> public interface TenantConfigurationServiceLocal {
> ```

Is ess implementation needed and provided?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797#-:-KozXzufa7wvyQuNt79h:b1i4yb2)*

**Comment by StavrevaS** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 74 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-Kp-Ntym6FVeAXHOoTW5:-Kp-Ntyn6XLv_OdONG9E:b-29ustx) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L74)):*
> ```Java
>     private TenantConfigurationService getTenantConfigService() throws NamingException {
>         if (tenantConfigurationService == null) {
>             tenantConfigurationService = (TenantConfigurationService) new InitialContext().lookup("java:global/oscm/oscm-tenantmgmt/TenantConfigurationBean!org.oscm.internal.intf.TenantConfigurationService");
> ```

For jndi lookup, we are using the ServiceLocator class. Please check how it is done on other places. In case of refactoring, this code can be forgotten.

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/bean/TenantConfigurationBean.java, line 8 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-Kp-Z4scWefzr-l6sr_u:-Kp-Z4scWefzr-l6sr_v:b-upvztd) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-tenantmgmt/javasrc/org/oscm/tenant/bean/TenantConfigurationBean.java#L8)):*
> ```Java
> package org.oscm.tenant.bean;
> 
> import java.util.HashMap;
> ```

It is better to have the cache in portal, it is used there (see MarketplaceCacheBean.java). Be careful about the code called in  methods annotated with @Schedule. In case of exception, after 2 attempts, the timer is expunged. Refreshing cache needs 3 queries, is this necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797)*

**Comment by grubskim** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantConfigurationService.java, line 18 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozWES3GCLb4RmpShZ9:-Kp0634Eb1rbU95DY2XF:b3tscg7) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantConfigurationService.java#L18)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

Is the remote access really needed? I think Local interface is sufficient. We will not call the bean from webservices or other distributed ears.
</blockquote></details>

Remote interface is needed as it is called from a different application (oscm-portal->oscm). I have removed the internal interface though.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 61 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozWyvfhdA0XN3n0sx1:-Kp0An_NSLe8QZHwtzQO:b30jxou) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L61)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

The authenticationHandler is being called with every request (probably). If true consider moving result of ejb calls to session if possible.
</blockquote></details>

It is called only during authentication.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 74 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-Kp-Ntym6FVeAXHOoTW5:-Kp0AyrVzOHGkIIdTFTA:bj3eoea) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L74)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

For jndi lookup, we are using the ServiceLocator class. Please check how it is done on other places. In case of refactoring, this code can be forgotten.
</blockquote></details>

Fixed, thanks.

---

*[oscm-tenantmgmt-intsvc/javasrc/org/oscm/tenant/local/TenantConfigurationServiceLocal.java, line 17 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozW_xc6Yz0YG75LgPE:-KpFKqUDe-8UHyWrLUdB:b-s3hmk9) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-tenantmgmt-intsvc/javasrc/org/oscm/tenant/local/TenantConfigurationServiceLocal.java#L17)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

Is ess implementation needed and provided?
</blockquote></details>

Not needed.

---

*[oscm-tenantmgmt/javasrc/org/oscm/tenant/bean/TenantConfigurationBean.java, line 8 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-Kp-Z4scWefzr-l6sr_u:-KpFKstoVM9xHVNx8Tmk:bilwvn1) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-tenantmgmt/javasrc/org/oscm/tenant/bean/TenantConfigurationBean.java#L8)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

It is better to have the cache in portal, it is used there (see MarketplaceCacheBean.java). Be careful about the code called in  methods annotated with @Schedule. In case of exception, after 2 attempts, the timer is expunged. Refreshing cache needs 3 queries, is this necessary?
</blockquote></details>

Moved cache to portal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797)*

**Comment by grubskim** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java, line 112 at r1](https://reviewable.io:443/reviews/servicecatalog/development/797#-KozXKn-fN22Wr9omffX:-KpFNECOJ4PJaOGSmw3F:bh7foxa) ([raw file](https://github.com/servicecatalog/development/blob/d7ea965273daebef8d0a47e39e2ec6d8bd83365a/oscm-portal/javasrc/org/oscm/ui/dialog/common/saml2/AuthenticationHandler.java#L112)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

Two ejb calls one by one which reaches for tenant specific data. May the both data be returned in the same time during one call? Small kittens are crying somewhere when performance is getting hit;)
</blockquote></details>

getTenantConfigService checks if the reference is null and does JNDI lookup only if it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797)*

**Comment by kowalczyka** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797)*

**Comment by kowalczyka** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797#-:-KpFNkb59DAk59ZTcqt6:bnfp4nl)*

**Comment by grubskim** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/797)*

**Comment by grubskim** [comment]
Merged.

**Pull request merged**
