### PR TITLE
Support for multitenancy

### PR DESCRIPTION
**Pull request by DawidCh**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/310)

### CODE REVIEW

**Comment by badziakp** [comment]
Reviewed 4 of 205 files at r1.
Review status: 4 of 205 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oscm-communicationservices/javasrc/org/oscm/communicationservice/bean/CommunicationServiceBean.java, line 272 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6QBOTy5O71KGTgGVH:-KS6QBOTy5O71KGTgGVI:b-rtylse) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-communicationservices/javasrc/org/oscm/communicationservice/bean/CommunicationServiceBean.java#L272)):*
> ```Java
>             if (tenantId != null && tenantId.trim().length() > 0) {
>                 removeTrailingSlashes(url);
>                 url.append("?tenantID=");
> ```

Harcoded values. ?tenantID= and UTF-8 should be moved to Constatnts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
Reviewed 60 of 205 files at r1, 2 of 13 files at r2.
Review status: 65 of 206 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantService.java, line 23 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6SB76SDKnwDt4A-si:-KS6SB76SDKnwDt4A-sj:b-ota16x) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantService.java#L23)):*
> ```Java
> @Remote
> public interface TenantService {
> ```

No javadocs.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/vo/VOMarketplace.java, line 40 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6TGY6V9o7SJFSHClS:-KS6TGY6V9o7SJFSHClT:b-ppp3bf) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-extsvc-internal/javasrc/org/oscm/internal/vo/VOMarketplace.java#L40)):*
> ```Java
>     private boolean restricted = false;
>     private boolean hasPublicLandingPage;
>     private String tenantTkey;
> ```

Check if can be removed.

---

*[oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java, line 20 at r2](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6UlTxyCC76qvcR0BP:-KS6UlTxyCC76qvcR0BQ:b-ota16x) ([raw file](https://github.com/servicecatalog/development/blob/27da52d416c2bf2ed66dd29f4394e2f18f83c597/oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java#L20)):*
> ```Java
> 
> @Remote
> public interface ManageTenantService {
> ```

No javadocs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Review status: 65 of 207 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/vo/VOMarketplace.java, line 40 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6TGY6V9o7SJFSHClS:-KSAKXO_Pc_rMeflCcR4:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-extsvc-internal/javasrc/org/oscm/internal/vo/VOMarketplace.java#L40)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> Check if can be removed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 5 of 205 files at r1.
Review status: 69 of 207 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[oscm-communicationservices/javasrc/org/oscm/communicationservice/bean/CommunicationServiceBean.java, line 272 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6QBOTy5O71KGTgGVH:-KSAMtEtrz7xV2j-aMiT:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-communicationservices/javasrc/org/oscm/communicationservice/bean/CommunicationServiceBean.java#L272)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> Harcoded values. ?tenantID= and UTF-8 should be moved to Constatnts
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
Reviewed 57 of 205 files at r1, 6 of 13 files at r2.
Review status: 130 of 208 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[oscm-operatorsvc/javasrc/org/oscm/operatorservice/bean/OperatorServiceBean.java, line 1098 at r2](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6Y-1weiOOswgnFrBL:-KS6Y-1weiOOswgnFrBM:b-mwheg3) ([raw file](https://github.com/servicecatalog/development/blob/27da52d416c2bf2ed66dd29f4394e2f18f83c597/oscm-operatorsvc/javasrc/org/oscm/operatorservice/bean/OperatorServiceBean.java#L1098)):*
> ```Java
>             userDetails.setOrganizationName((String) row[2]);
>             userDetails.setOrganizationId((String) row[3]);
>             result.add(userDetails);
> ```

Indexes: 0, 1, 2, 3 - to private static final int...

---

*[oscm-portal/javasrc/org/oscm/ui/beans/UpdateMarketplaceBean.java, line 338 at r3](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6__OF6AAPH7bJyGc9:-KS6__OF6AAPH7bJyGcA:bhbd58n) ([raw file](https://github.com/servicecatalog/development/blob/43d7fb11f86050ae26d8c3bbd05d2f2b70785908/oscm-portal/javasrc/org/oscm/ui/beans/UpdateMarketplaceBean.java#L338)):*
> ```Java
>         return selectOrganizationIncludeBean;
>     }
>     
> ```

The same method exists in NewMarketplaceBean. It's code duplication.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java, line 133 at r4](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6dHhzS8JNB9eepIBc:-KS6dHi-OwrWDzjQXMyT:bai5ncl) ([raw file](https://github.com/servicecatalog/development/blob/93370d696d2fb5752c2a5faa038f0c2626fc756a/oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java#L133)):*
> ```Java
>         if (dataTableHeaders == null || dataTableHeaders.isEmpty()) {
>             try {
>                 dataTableHeaders = Arrays.asList("userId", "EMail", "organizationName", "organizationId");
> ```

Why VO objects are using for presentation?
VO should be translated to PO. Column headers should be based on PO fields names.
This solution breaks our presenation layer conception.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java, line 270 at r4](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6eJl1gEJ6CesX1Bq4:-KS6eJl2Q2cAwPgw_seW:b-kpu91g) ([raw file](https://github.com/servicecatalog/development/blob/93370d696d2fb5752c2a5faa038f0c2626fc756a/oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java#L270)):*
> ```Java
>     List<Marketplace> getSelectableMarketplaces() {
>         if (isLoggedInAndPlatformOperator()) {
>             if (marketplaces.isEmpty()) {
> ```

If marketplaces list is empty then marketplaces = new ArrayList<>(); is not needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
:lgtm:

---

Reviewed 9 of 205 files at r1, 1 of 13 files at r2, 1 of 1 files at r4, 1 of 7 files at r5.
Review status: 138 of 208 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310#-:-KSAbm79r16zHXglaGBB:bnfp4nl)*

**Comment by DawidCh** [comment]
Reviewed 43 of 205 files at r1, 1 of 13 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 7 files at r5.
Review status: 155 of 208 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[oscm-operatorsvc/javasrc/org/oscm/operatorservice/bean/OperatorServiceBean.java, line 1098 at r2](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6Y-1weiOOswgnFrBL:-KSAcVuBWoJ7tWzGAg5E:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/27da52d416c2bf2ed66dd29f4394e2f18f83c597/oscm-operatorsvc/javasrc/org/oscm/operatorservice/bean/OperatorServiceBean.java#L1098)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> Indexes: 0, 1, 2, 3 - to private static final int...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 38 of 205 files at r1, 3 of 7 files at r5.
Review status: 196 of 208 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[oscm-portal/javasrc/org/oscm/ui/beans/UpdateMarketplaceBean.java, line 338 at r3](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6__OF6AAPH7bJyGc9:-KSAckcMvh3uhAGuFzAj:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/43d7fb11f86050ae26d8c3bbd05d2f2b70785908/oscm-portal/javasrc/org/oscm/ui/beans/UpdateMarketplaceBean.java#L338)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> The same method exists in NewMarketplaceBean. It's code duplication.
</details>
Done.

---

*[oscm-tenantmgmt/readme.txt, line 1 at r5](https://reviewable.io:443/reviews/servicecatalog/development/310#-KSAeHbiv6IOVK6W8u6u:-KSAeHbjjEfG5uYsNXka:b-72sxte) ([raw file](https://github.com/servicecatalog/development/blob/8ef710d867bfed6c6e616c60e1df47e908118eea/oscm-tenantmgmt/readme.txt#L1)):*
> ```
> The marketplace management service implementation.
> ```

Is it marketplace management service?

---

*[oscm-tenantmgmt-intsvc/readme.txt, line 1 at r5](https://reviewable.io:443/reviews/servicecatalog/development/310#-KSAeRVQx5eXoj-YLAKa:-KSAeRVQx5eXoj-YLAKb:b-72sxte) ([raw file](https://github.com/servicecatalog/development/blob/8ef710d867bfed6c6e616c60e1df47e908118eea/oscm-tenantmgmt-intsvc/readme.txt#L1)):*
> ```
> The marketplace management service implementation.
> ```

Is it marketplace management service?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
Reviewed 54 of 205 files at r1, 1 of 3 files at r3, 3 of 7 files at r5, 2 of 10 files at r6.
Review status: 196 of 211 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
Reviewed 1 of 7 files at r5.
Review status: 197 of 211 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 1 of 205 files at r1.
Review status: 197 of 211 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 1 of 205 files at r1, 1 of 2 files at r7.
Review status: 198 of 211 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[oscm-tenantmgmt/readme.txt, line 1 at r5](https://reviewable.io:443/reviews/servicecatalog/development/310#-KSAeHbiv6IOVK6W8u6u:-KSAzXUKK1_wc4dX2S8z:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/8ef710d867bfed6c6e616c60e1df47e908118eea/oscm-tenantmgmt/readme.txt#L1)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary>
> Is it marketplace management service?
</details>
Done.

---

*[oscm-tenantmgmt-intsvc/readme.txt, line 1 at r5](https://reviewable.io:443/reviews/servicecatalog/development/310#-KSAeRVQx5eXoj-YLAKa:-KSAz_8OnzG7430az9z_:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/8ef710d867bfed6c6e616c60e1df47e908118eea/oscm-tenantmgmt-intsvc/readme.txt#L1)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary>
> Is it marketplace management service?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 199 of 199 files at r9, 1 of 1 files at r10, 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 31 of 31 files at r12.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantService.java, line 23 at r1](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6SB76SDKnwDt4A-si:-KSGNKe1RTVss4DHmBLh:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/e3fcc78e3d858450d0dde521de005c2f7b303b55/oscm-extsvc-internal/javasrc/org/oscm/internal/intf/TenantService.java#L23)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> No javadocs.
</details>
Done.

---

*[oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java, line 20 at r2](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6UlTxyCC76qvcR0BP:-KSGNVC1Zb8WzcUJ059n:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/27da52d416c2bf2ed66dd29f4394e2f18f83c597/oscm-internal-interfaces/javasrc/org/oscm/internal/tenant/ManageTenantService.java#L20)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> No javadocs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 2 of 2 files at r13.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by DawidCh** [comment]
Reviewed 2 of 4 files at r14, 1 of 10 files at r15, 4 of 5 files at r18, 1 of 2 files at r20, 6 of 18 files at r21, 46 of 77 files at r22, 1 of 5 files at r23.
Review status: 216 of 274 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java, line 133 at r4](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6dHhzS8JNB9eepIBc:-KTwwGdhQBKp4Q_o0IoB:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/93370d696d2fb5752c2a5faa038f0c2626fc756a/oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java#L133)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> Why VO objects are using for presentation?
> VO should be translated to PO. Column headers should be based on PO fields names.
> This solution breaks our presenation layer conception.
</details>
Done.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java, line 270 at r4](https://reviewable.io:443/reviews/servicecatalog/development/310#-KS6eJl1gEJ6CesX1Bq4:-KTwxjpjN1TvW3kTHc9Y:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/93370d696d2fb5752c2a5faa038f0c2626fc756a/oscm-portal/javasrc/org/oscm/ui/dialog/classic/operator/OperatorManageUsersCtrl.java#L270)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> If marketplaces list is empty then marketplaces = new ArrayList<>(); is not needed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Comment by badziakp** [comment]
Reviewed 1 of 199 files at r9, 2 of 4 files at r14, 5 of 10 files at r15, 2 of 3 files at r16, 6 of 7 files at r19, 8 of 18 files at r21, 62 of 77 files at r22, 5 of 5 files at r23.
Review status: 270 of 274 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/310)*

**Pull request merged**
