### PR TITLE
 Added Public IP, Subnet and Security group functionality in AWS controller (oscm-app-aws)

### PR DESCRIPTION
**Pull request by pujarisat**
Hi Team,

We have added below functionality on AWS controller and also we have modified the unit test classes as per the new functionality 

1)	Apply the public IP to the AWS instance
2)	Add the subnet to the AWS instance(Select the existing subnet and apply same to AWS instance)
3)	Add security group to the AWS instance 
4)	Add disk size to AWS instance

-Thanks
Satling

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/349)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Please check travis ci, why the tests are not running. We cannot merge without this check.

**Comment by StavrevaS** [comment]
Reviewed 8 of 8 files at r1, 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[oscm-app-aws/.classpath, line 24 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJRvEuCqfnEMniBhiE:-KTJRvEuCqfnEMniBhiF:bygkftw) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/.classpath#L24)):*
> ```XML
> 	<classpathentry combineaccessrules="false" kind="src" path="/oscm-common"/>
> 	<classpathentry combineaccessrules="false" kind="src" path="/oscm-extsvc-internal"/>
> 	<classpathentry kind="lib" path="/libraries/aws/javalib/jackson-databind-2.2.3.jar"/>
> ```

Return back to the old dependencies where possible (see comment by ivy-build.xml)

---

*[oscm-app-aws/package.properties, line 19 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJS9Sy3rH6SbLoUDyJ:-KTJS9Sy3rH6SbLoUDyK:b-ye79es) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/package.properties#L19)):*
> ```INI
> oscm-app-aws.ear@lib = ${workspace.dir}/libraries/apache-httpcore/javalib/[fluent-hc-4.3.1.jar]
> oscm-app-aws.ear@lib = ${workspace.dir}/libraries/apache-codec/javalib/[*.jar]
> oscm-app-aws.ear@lib = ${workspace.dir}/libraries/aws/javalib/[*.jar]
> ```

Consider comment for ivy-build.xml

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 70 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJoyW-oUWF_CfnW64g:-KTJoyW-oUWF_CfnW64h:bc44472) ([raw file](https://github.com/servicecatalog/development/blob/01cb08c39ae795207e6e6d5696aaa9a6ed448387/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L70)):*
> ```Java
> 	private static final String HTTPS_PROXY_HOST = "https.proxyHost";
> 	private static final String HTTPS_PROXY_PORT = "https.proxyPort";
> 	private static final String HTTPS_PROXY_USER = "https.proxyUser";
> ```

Why the user and password are removed?

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 230 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJpFzGVhuaL5c-dpLx:-KTJpFzGVhuaL5c-dpLy:bmoho82) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L230)):*
> ```Java
>         List<Image> images = describeImagesResult.getImages();
>         for (Image image : images) {
>             System.out.println(image.getImageId() + "=="
> ```

Remove println, move info to debug statement.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 235 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJpPX2896jkR9u12XI:-KTJpPX2896jkR9u12XJ:b-wm2q8m) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L235)):*
> ```Java
>             return image;
>         }
>         throw new APPlatformException("error_invalid_image " + amiID);
> ```

Use Messages.getAll() like in the original code, why this is removed? This error massage may be used from APP for mail notification and should be localized.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 259 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJqJkuIKCxyzna8ggu:-KTJqJkuIKCxyzna8ggv:bxxcq1b) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L259)):*
> ```Java
> 
>         }
>         throw new APPlatformException(
> ```

Define localized error message, like in resolveAMI() method.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 267 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJrGCAlsFpCrpAI7lK:-KTJrGCAlsFpCrpAI7lL:b-77055f) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L267)):*
> ```Java
>      * Checks whether exiting SecurityGroups is present.
>      * 
>      * @param securityGroupNames
> ```

Describe param vpcId.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 305 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJqgJQQQywDvtNMGuG:-KTJqgJVj7Om1wWOS-_s:by7i8qn) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L305)):*
> ```Java
>                     }
>                     sb.append(name);
>                 }
> ```

Define localized error message like in removeAMI() method.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 338 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJs7loRibTvJ_Ej9wI:-KTJs7loRibTvJ_Ej9wJ:b6iln0u) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L338)):*
> ```Java
>                 "runInstancesRequest : " + " image ID : " + image.getImageId()
>                         + " insatance type : " + ph.getInstanceType()
>                         + " keypairname : " + ph.getKeyPairName());
> ```

Do not log keypair name, even for debug purposes.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 350 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJsqY3aFpixpIwcRQZ:-KTJsYFks_aRduhBvWFE:bajt7hx) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L350)):*
> Boolean.parseBoolean(ph.getPublicIp()))

It would be good to trim the string to be parsed if it is not null.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 385 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJv8zpDoMc8LlHKiVI:-KTJv8zqqSPRZnUGLAy1:b4m6vhx) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L385)):*
> ```Java
>                             if (diskSize.intValue() < ebs.getVolumeSize()
>                                     .intValue()) {
>                                 diskSize = ebs.getVolumeSize().intValue();
> ```

Too many code duplication in the if statement. Please refactor this.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 417 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJvaMOZ6sji6e1nonA:-KTJvaMOZ6sji6e1nonB:b-yfeqem) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L417)):*
> ```Java
>                 }
>             }
>         } catch (NumberFormatException e) {
> ```

Please convert this to proper APPlatformException, with localized error text

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 569 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJvzN49VkKWIkIJw48:-KTJvzN5IA_PFOJjCD1y:b-xfmhbc) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L569)):*
> ```Java
>         List<Tag> tags = new ArrayList<Tag>();
>         tags.add(new Tag(PropertyHandler.TAG_NAME, ph.getInstanceName()));
>         // tags.add(new Tag(PropertyHandler.TAG_SUBSCRIPTION_ID,
> ```

Why these tags are removed?

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java, line 496 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJwGTv5bw-fqvJKXEo:-KTJwGTwL7oPZ1wlE5We:bfu3u3) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java#L496)):*
> ```Java
>                     Messages.getAll("error_missing_instancetype"));
>         }
>         if (isNullOrEmpty(ph.getDiskSize())) {
> ```

PLease check if this code about disk size and subnet is necesssary here. The method deals with operations like start/stop instance, not provisioning actions like create instance.

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java, line 231 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJw_y2HEb8POnXMgEY:-KTJw_y2HEb8POnXMgEZ:b-t3geuj) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java#L231)):*
> ```Java
> 
>         case CREATING:
>             LOGGER.info("trying to check sataus");
> ```

Check spelling. Make debug statement.

---

*[oscm-app-aws/resources/TechnicalService_AWS.xml, line 83 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJPJAn41JTMpnzQY1W:-KTJPJAn41JTMpnzQY1X:bsnqig2) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/resources/TechnicalService_AWS.xml#L83)):*
> ```XML
>       <LocalizedDescription locale="en">Region</LocalizedDescription>
>     </ParameterDefinition>
> 	
> ```

Can you explain, why these parameters should be mandatory?

---

*[oscm-build/ivy-build.xml, line 103 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJPWlSrt-hzHLDp_vt:-KTJPWlSrt-hzHLDp_vu:bqp1xqe) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-build/ivy-build.xml#L103)):*
> ```XML
>     <copy file="${ivy.lib.dir}/aws-java-sdk-core-1.11.37.jar" todir="${root.dir}/libraries/aws/javalib"></copy>
>     <copy file="${ivy.lib.dir}/aws-java-sdk-ec2-1.11.37.jar" todir="${root.dir}/libraries/aws/javalib"></copy>
>     <copy file="${ivy.lib.dir}/jackson-databind-2.2.3.jar" todir="${root.dir}/libraries/aws/javalib"></copy>
> ```

Most of the libraries are already included in the right or older version. Please update where necessary and adapt packaging where necessary.

Jackson libraries:
already included in this file in the requested version in /libraries/jackson/javalib/. They should not be duplicated for aws. 
Http libraries:
already included in /libraries/apache-httpcore/javalib in different versions from requested. Please update here.
Joda time library:
Include in new dir /libraries/joda-time/javalib

---

*[oscm-build/ivy.xml, line 525 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJRWDSfu7GrmmbFvX5:-KTJRWDSfu7GrmmbFvX6:bcku86e) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-build/ivy.xml#L525)):*
> ```XML
>         <dependency org="wsdl4j" name="wsdl4j" rev="1.6.1" transitive="false"/>
>         <dependency org="com.google.code.gson" name="gson" rev="2.6.2" transitive="false"/>
>         
> ```

Adapt if ivy-build.xml is changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/349)*

**Comment by StavrevaS** [comment]
Reviewed 7 of 7 files at r3.
Review status: 30 of 32 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[oscm-app-aws/.classpath, line 24 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJRvEuCqfnEMniBhiE:-KTPGdd5TtlLQTl8GsSb:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/.classpath#L24)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Return back to the old dependencies where possible (see comment by ivy-build.xml)
</details>
OK

---

*[oscm-app-aws/package.properties, line 19 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJS9Sy3rH6SbLoUDyJ:-KTPGiojx9pCBuHEG8BB:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/package.properties#L19)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Consider comment for ivy-build.xml
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 70 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJoyW-oUWF_CfnW64g:-KTPGw2ZpgG7kLEPxnC7:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/01cb08c39ae795207e6e6d5696aaa9a6ed448387/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L70)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Why the user and password are removed?
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 230 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJpFzGVhuaL5c-dpLx:-KTPH3r7KVl_oTKVF0sk:b-tu6uf1) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L230)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Remove println, move info to debug statement.
</details>
Describe in the debug statement the values (e.g "Image ID: "+image.getImageId() etc)

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 235 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJpPX2896jkR9u12XI:-KTPHLk7IO6dHwSdXeZm:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L235)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Use Messages.getAll() like in the original code, why this is removed? This error massage may be used from APP for mail notification and should be localized.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 259 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJqJkuIKCxyzna8ggu:-KTPHQTOdrMKbTW_1mv7:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L259)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Define localized error message, like in resolveAMI() method.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 267 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJrGCAlsFpCrpAI7lK:-KTPHcCYyutOzWR-U0fJ:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L267)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Describe param vpcId.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 305 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJqgJQQQywDvtNMGuG:-KTPHgHIZ-u1Wjhfz4VP:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L305)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Define localized error message like in removeAMI() method.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 338 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJs7loRibTvJ_Ej9wI:-KTPHi42CAxEjxSV_IPg:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L338)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Do not log keypair name, even for debug purposes.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 350 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJsqY3aFpixpIwcRQZ:-KTPHs06F-71mnomOxJ7:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L350)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> > Boolean.parseBoolean(ph.getPublicIp()))
> 
> It would be good to trim the string to be parsed if it is not null.
> 
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 385 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJv8zpDoMc8LlHKiVI:-KTPHuXezPNn7m6Hxacp:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L385)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Too many code duplication in the if statement. Please refactor this.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 417 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJvaMOZ6sji6e1nonA:-KTPIWCiGOH9wOsIIvzB:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L417)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Please convert this to proper APPlatformException, with localized error text
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 569 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJvzN49VkKWIkIJw48:-KTPI4oFKa-fMPEC17_h:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L569)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Why these tags are removed?
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java, line 274 at r3](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTPHSYLtwsNKYoHgn1i:-KTPHSYM-2WTWYiIOXTQ:bm98ehf) ([raw file](https://github.com/servicecatalog/development/blob/ece42bba3a13c0db67a76f7597eb2d24a9bdec7e/oscm-app-aws/javasrc/org/oscm/app/aws/EC2Communication.java#L274)):*
> ```Java
>         throw new APPlatformException(
>                 Messages.getAll("error_invalid_subnet_id ") + subnetString);
> ```

White space before closing "?

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java, line 496 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJwGTv5bw-fqvJKXEo:-KTPIck1Rro0F6fu-xnC:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java#L496)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> PLease check if this code about disk size and subnet is necesssary here. The method deals with operations like start/stop instance, not provisioning actions like create instance.
</details>
OK

---

*[oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java, line 231 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJw_y2HEb8POnXMgEY:-KTPIgZ6-Ey94Ezl02mo:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/javasrc/org/oscm/app/aws/controller/EC2Processor.java#L231)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Check spelling. Make debug statement.
</details>
OK

---

*[oscm-app-aws/resources/TechnicalService_AWS.xml, line 83 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJPJAn41JTMpnzQY1W:-KTPIkw0ESJp6Hy0rMYh:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-app-aws/resources/TechnicalService_AWS.xml#L83)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Can you explain, why these parameters should be mandatory?
</details>
OK

---

*[oscm-build/ivy-build.xml, line 103 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJPWlSrt-hzHLDp_vt:-KTPIpPF2C8KE9GBpvY6:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-build/ivy-build.xml#L103)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Most of the libraries are already included in the right or older version. Please update where necessary and adapt packaging where necessary.
> 
> Jackson libraries:
> already included in this file in the requested version in /libraries/jackson/javalib/. They should not be duplicated for aws. 
> Http libraries:
> already included in /libraries/apache-httpcore/javalib in different versions from requested. Please update here.
> Joda time library:
> Include in new dir /libraries/joda-time/javalib
</details>
OK

---

*[oscm-build/ivy.xml, line 525 at r2](https://reviewable.io:443/reviews/servicecatalog/development/349#-KTJRWDSfu7GrmmbFvX5:-KTPLE81CXRLtWhntXa4:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/a94face0a470a8b4d16fa83fd2969f4be6fb2234/oscm-build/ivy.xml#L525)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary>
> Adapt if ivy-build.xml is changed.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/349)*

**Comment by StavrevaS** [comment]
Please adapt the ivy scripts to copy the new versions of httpcore and httpclient libraries. Look in all classpath files and package.properties files for old versions and adapt. See if you can compile the whole source code after it.
I think that is the reason the Travis CI is failing.

**Comment by StavrevaS** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/349)*

**Comment by pujarisat** [comment]
Hi ,
updated the ivy-build.xml file. Till sowing error for new version httpcore-4.4.1.jar. earlier was showing for old version httpcore-4.3.jar  jar 


BUILD FAILED
/home/travis/build/servicecatalog/development/oscm-build/cruisecontrol.xml:136: The following error occurred while executing this line:
/home/travis/build/servicecatalog/development/oscm-build/ivy-build.xml:55: Warning: Could not find file /home/travis/build/servicecatalog/development/oscm-build/lib/httpcore-4.4.1.jar to copy.

-Thanks 
Satling

**Comment by pujarisat** [comment]
Hi Team,

I have changed version of below jar in ivy.xml file. However I am getting another error in Travis CI build log .

BUILD FAILED
/home/travis/build/servicecatalog/development/oscm-build/cruisecontrol.xml:45: The following error occurred while executing this line:
/home/travis/build/servicecatalog/development/oscm-build/build.xml:371: The following error occurred while executing this line:
/home/travis/build/servicecatalog/development/oscm-build/build.xml:208: The following error occurred while executing this line:
/home/travis/build/servicecatalog/development/oscm-build/defaultprojectbuild.xml:35: Class path entry does not exist: /home/travis/build/servicecatalog/development/libraries/apache-axis2-lib/javalib/httpcore-4.3.jar
Total time: 1 minute 39 seconds

Kindly suggest or help.

-Thanks
Satling Pujari

**Comment by GoebelL** [comment]
That's fine. All points are solved. 

I accept the pull request.

**Pull request merged**
