### PR TITLE
Hotfix/issue 742

### PR DESCRIPTION
**Pull request by grubskim**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/801)

### CODE REVIEW

**Comment by badziakp** [comment]
Reviewed 17 of 19 files at r1.
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java, line 14 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-Kpnj7BQzfNDvMP6vkH1:-Kpnj7BQzfNDvMP6vkH2:b-kiuqyi) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java#L14)):*
> ```Java
> 
>     public MarketplaceValidationException() {
>         super();
> ```

Parent constructor doesn't need to be called here

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java, line 306 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-KpnnKpJQTuBWLIOVtnB:-KpnnKpJQTuBWLIOVtnC:b22kls8) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java#L306)):*
>  private Marketplace persistMarketplace(boolean isMpIdProvided, Marketplace mpNew, VOMarketplace marketplace) throws MarketplaceValidationException {
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>         Marketplace mp;
>         if (isMpIdProvided) {
>             mp = persistMarketplaceWithSpecifiedId(mpNew, marketplace.getMarketplaceId());
>         } else {
>             mp = persistMarketplace(mpNew,
>                     marketplace.getOwningOrganizationId());
>         }
>         return mp;
>     }
</details>

Refactor it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by grubskim** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java, line 14 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-Kpnj7BQzfNDvMP6vkH1:-KpnobKbYN3W6o6flaCq:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java#L14)):*
<details><summary><i>Previously, badziakp wrote…</i></summary><blockquote>

Parent constructor doesn't need to be called here
</blockquote></details>

Done.

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java, line 306 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-KpnnKpJQTuBWLIOVtnB:-KpnogMlhQtLaJLAjsbf:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java#L306)):*
<details><summary><i>Previously, badziakp wrote…</i></summary><blockquote>

>  private Marketplace persistMarketplace(boolean isMpIdProvided, Marketplace mpNew, VOMarketplace marketplace) throws MarketplaceValidationException {
>         Marketplace mp;
>         if (isMpIdProvided) {
>             mp = persistMarketplaceWithSpecifiedId(mpNew, marketplace.getMarketplaceId());
>         } else {
>             mp = persistMarketplace(mpNew,
>                     marketplace.getOwningOrganizationId());
>         }
>         return mp;
>     }

Refactor it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by DawidCh** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by DawidCh** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java, line 14 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-Kpnj7BQzfNDvMP6vkH1:-KqRqu8JnzmRfklV5Mzj:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java#L14)):*
<details><summary><i>Previously, grubskim (Michał Grubski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java, line 306 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-KpnnKpJQTuBWLIOVtnB:-KqRqqH8-9IM0glo__Cg:b32w0x) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java#L306)):*
<details><summary><i>Previously, grubskim (Michał Grubski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by DawidCh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801#-:-KqRr58LWll3xJWwikeP:bnfp4nl)*

**Comment by DawidCh** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java, line 14 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-Kpnj7BQzfNDvMP6vkH1:-KqRrGkKoTUQx6pijq7V:b-z9i4hn) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-extsvc-internal/javasrc/org/oscm/internal/types/exception/MarketplaceValidationException.java#L14)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

OK
</blockquote></details>

LGTM, ok.

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java, line 306 at r1](https://reviewable.io:443/reviews/servicecatalog/development/801#-KpnnKpJQTuBWLIOVtnB:-KqRrA2BZxazTmHAJuIO:b-smsv3r) ([raw file](https://github.com/servicecatalog/development/blob/2667037ffffe7fedd9d2a8a14634c9786f1ef330/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java#L306)):*
<details><summary><i>Previously, DawidCh (Dawid) wrote…</i></summary><blockquote>

OK
</blockquote></details>

LGTM, ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by StavrevaS** [comment]
Reviewed 16 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[oscm-common/javares/ExceptionMessages_en.properties, line 393 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZYML3Wj_NnttH5pr:-KtQZYML3Wj_NnttH5ps:b-6tsayg) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-common/javares/ExceptionMessages_en.properties#L393)):*
> ```INI
> ex.UpdateConstraintException.TENANT_SETTING=The tenant setting {0} could not be updated.
> ex.InvalidSigningAlgorithmException=Unsupported SAML signing algorithm.
> ex.MarketplaceValidationException=Provided Marketplace ID is already in use.
> ```

Check end of line, there is some white space character?

---

*[oscm-common/javares/ExceptionMessages_ja.properties, line 392 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZQpqu1vUyzbkgavJ:-KtQZQpqu1vUyzbkgavK:b-6tsayg) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-common/javares/ExceptionMessages_ja.properties#L392)):*
> ```INI
> ex.UpdateConstraintException.TENANT_SETTING=Tenant setting {0} could not be updated.
> ex.InvalidSigningAlgorithmException=Unsupported SAML signing algorithm.
> ex.MarketplaceValidationException=Provided Marketplace ID is already in use.
> ```

Check end of line, there is some white space character?

---

*[oscm-common/javares/LogMessages.properties, line 652 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQYJYocSlSJOq-Srk0:-KtQYJYpF5g9DFP3jcIw:b-ixffxx) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-common/javares/LogMessages.properties#L652)):*
> ```INI
> 70316=Error reading the encryption key file.
> 70317=Bad encrypted value found.
> 70318=Unsupported SAML signing algorithm.
> ```

Please check the log identifier, it does not match the message here.

---

*[oscm-extsvc/javasrc/org/oscm/types/exceptions/MarketplaceValidationException.java, line 14 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZpP2o1maYwaYvw57:-KtQZpP2o1maYwaYvw58:bolrmf7) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-extsvc/javasrc/org/oscm/types/exceptions/MarketplaceValidationException.java#L14)):*
> ```Java
> /**
>  * Created by PLGrubskiM on 2017-07-21.
>  */
> ```

Remove "created by", this is the external interface

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java, line 273 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZz9o7gIJlJF8grj_:-KtQZz9o7gIJlJF8grja:b-funh5h) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceBean.java#L273)):*
> ```Java
>         if (marketplace.getMarketplaceId() == null) {
>             marketplace.setMarketplaceId("1"); // dummy Id - will be changed.
>         } else {
> ```

Is only null check enough? What about empty string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by StavrevaS** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by DawidCh** [comment]
Review status: 19 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-common/javares/ExceptionMessages_en.properties, line 393 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZYML3Wj_NnttH5pr:-KtQo7ZEgQBt6c6oxeaH:bia1ry3) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-common/javares/ExceptionMessages_en.properties#L393)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

Check end of line, there is some white space character?
</blockquote></details>

No. IT is fine.

---

*[oscm-common/javares/ExceptionMessages_ja.properties, line 392 at r2](https://reviewable.io:443/reviews/servicecatalog/development/801#-KtQZQpqu1vUyzbkgavJ:-KtQoBOWlQ26cX5ObZHq:bia1ry3) ([raw file](https://github.com/servicecatalog/development/blob/7f09fc6b0913ad77d825be9e4d2e6f5e377fdbac/oscm-common/javares/ExceptionMessages_ja.properties#L392)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

Check end of line, there is some white space character?
</blockquote></details>

No. IT is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Comment by StavrevaS** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/801)*

**Pull request merged**
