### PR TITLE
Added check for displaying revenue shares when external billing syste…

### PR DESCRIPTION
**Pull request by kowalczyka**
…m is used

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/39)

### CODE REVIEW

**Comment by badziakp** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[oscm-portal/WebContent/service/publish.xhtml, line 86 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/39#-KFJEzO8vmCD7FjGu1Fx:-KFJEzO8vmCD7FjGu1Fy:-1537921379) ([raw file](https://github.com/servicecatalog/development/blob/d1f0f7f8bbd7e84613e7fcb8341c30dd7efd62bd/oscm-portal/WebContent/service/publish.xhtml#L86)):*
Changes can be done in the controller 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/39)*

**Comment by badziakp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/marketableservice/MarketableServicePublishCtrl.java, line 130 \[r2\]](https://reviewable.io:443/reviews/servicecatalog/development/39#-KFNzq6-245NLECtDf5L:-KFNz3vdBdAJSqH4Q1ud:1586044304) ([raw file](https://github.com/servicecatalog/development/blob/a37a9e3c53b7f4c52ff07f4ef58dccd4bd9e914c/oscm-portal/javasrc/org/oscm/ui/dialog/classic/marketableservice/MarketableServicePublishCtrl.java#L130)):*
comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/39)*

**Comment by kowalczyka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-portal/javasrc/org/oscm/ui/dialog/classic/marketableservice/MarketableServicePublishCtrl.java, line 130 \[r2\]](https://reviewable.io:443/reviews/servicecatalog/development/39#-KFNzq6-245NLECtDf5L:-KFO-W7bH0c1dDZTovLS:-499146009) ([raw file](https://github.com/servicecatalog/development/blob/a37a9e3c53b7f4c52ff07f4ef58dccd4bd9e914c/oscm-portal/javasrc/org/oscm/ui/dialog/classic/marketableservice/MarketableServicePublishCtrl.java#L130)):*
Done.

---

*[oscm-portal/WebContent/service/publish.xhtml, line 86 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/39#-KFJEzO8vmCD7FjGu1Fx:-KFO-he_wbHpByzT9YRV:-499146009) ([raw file](https://github.com/servicecatalog/development/blob/d1f0f7f8bbd7e84613e7fcb8341c30dd7efd62bd/oscm-portal/WebContent/service/publish.xhtml#L86)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/39)*

**Comment by badziakp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/39)*

**Pull request merged**
