### PR TITLE
Omit Billing Address and Payment Info in the Subscription Process

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/53)

### CODE REVIEW

**Comment by kowalczyka** [comment]
Reviewed 1 of 40 files at r1.
Review status: 1 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 39 of 40 files at r1.
Review status: 40 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 2 of 10 files at r3, 12 of 16 files at r4, 39 of 40 files at r5, 6 of 9 files at r6, 2 of 8 files at r7, 3 of 3 files at r8.
Review status: 66 of 85 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 10 files at r3.
Review status: 62 of 90 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 10 files at r3, 1 of 8 files at r7, 1 of 4 files at r9, 3 of 5 files at r10.
Review status: 68 of 90 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Review status: 68 of 90 files reviewed at latest revision, 2 unresolved discussions.

---

*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 1720 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGMuruGNjB06Lel9T9Q:-KGMuruHw1uEeA9j5GM2:-38619126) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L1720)):*
Translation is missing.

---

*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 1721 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGMv7HC4IOVuOGlJyLj:-KGMv7HC4IOVuOGlJyLk:-38619126) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L1721)):*
Translation is missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 2 of 8 files at r7.
Review status: 70 of 90 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 2 of 5 files at r10.
Review status: 72 of 90 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 3 of 10 files at r3, 1 of 40 files at r5.
Review status: 76 of 90 files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/bean/SubscriptionServiceBean.java, line 387 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGN1fbHxVgjW3e6FOrZ:-KGN1fbHxVgjW3e6FOr_:-637233885) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/bean/SubscriptionServiceBean.java#L387)):*
Please change method name.

---

*[oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/dao/BillingContactDao.java, line 30 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGN1RrI12t_l7vqoEEz:-KGN1RrI12t_l7vqoEF-:-637233885) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/dao/BillingContactDao.java#L30)):*
Please change method name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Reviewed 2 of 2 files at r12, 1 of 1 files at r13.
Review status: 79 of 90 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 1 of 10 files at r3, 3 of 16 files at r4, 2 of 8 files at r7, 1 of 4 files at r9, 7 of 7 files at r11.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 1 of 40 files at r1, 5 of 10 files at r3, 1 of 40 files at r5, 3 of 8 files at r7, 1 of 4 files at r9, 5 of 5 files at r10, 2 of 2 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by kowalczyka** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, line 1720 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGMuruGNjB06Lel9T9Q:-KGVy0BIYt8C743ZkcfP:-499146009) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties#L1720)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties, line 1721 \[r11\]](https://reviewable.io:443/reviews/servicecatalog/development/53#-KGMv7HC4IOVuOGlJyLj:-KGVy6N5sr2CQgaWMrGS:1706341799) ([raw file](https://github.com/servicecatalog/development/blob/ac2b9226b0ce9ec09d66b31382275527f558ff92/oscm-portal/javares/org/oscm/ui/resources/Messages_ja.properties#L1721)):*
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 248 of 249 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, 3 of 3 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 4 of 22 files at r19.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Comment by badziakp** [comment]
Reviewed 11 of 12 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/53)*

**Pull request merged**
