### PR TITLE
Issue1 enhancments

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/897)

### CODE REVIEW

**Comment by StavrevaS** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[oscm-app/javasrc/org/oscm/app/v2_0/service/ServiceInstanceServiceBean.java, line 349 at r1](https://reviewable.io:443/reviews/servicecatalog/development/897#-L3b1z5YrLkVdCIg5am1:-L3b1z5ZXdnl9usuKzfq:bupag4d) ([raw file](https://github.com/servicecatalog/development/blob/d64e39bbd2a4b1f742db44e61bb67624b8f3b715/oscm-app/javasrc/org/oscm/app/v2_0/service/ServiceInstanceServiceBean.java#L349)):*
> ```Java
>                         createInstanceResult(dbInstance), false,
>                         new APPlatformException(
>                                 "Instance creation has been aborted manually"));
> ```

This message should be localized. "Manually" is not very informative for the customer. Better would be something like "The subscription cannot be completed, because a service instance cannot be provided. Please contact your service supplier for more details, or terminate the subscription and try again."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/897)*

**Comment by kowalczyka** [comment]
Review status: 17 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[oscm-app/javasrc/org/oscm/app/v2_0/service/ServiceInstanceServiceBean.java, line 349 at r1](https://reviewable.io:443/reviews/servicecatalog/development/897#-L3b1z5YrLkVdCIg5am1:-L3bl1zmx7--Vw5G-nHJ:b-896fix) ([raw file](https://github.com/servicecatalog/development/blob/d64e39bbd2a4b1f742db44e61bb67624b8f3b715/oscm-app/javasrc/org/oscm/app/v2_0/service/ServiceInstanceServiceBean.java#L349)):*
<details><summary><i>Previously, StavrevaS (Suzana Stavreva) wrote…</i></summary><blockquote>

This message should be localized. "Manually" is not very informative for the customer. Better would be something like "The subscription cannot be completed, because a service instance cannot be provided. Please contact your service supplier for more details, or terminate the subscription and try again."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/897)*

**Comment by GoebelL** [comment]
:lgtm:

---

Review status: 17 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/897#-:-L3cCrKP86i_wExFjS02:bnfp4nl)*

**Comment by GoebelL** [comment]
Reviewed 17 of 18 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/897)*

**Comment by StavrevaS** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/897)*

**Pull request merged**
