### PR TITLE
Restrict the access to marketplaces to organizations

### PR DESCRIPTION
**Pull request by badziakp**
#22 
Pull request for issue 3196

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/79)

### CODE REVIEW

**Comment by badziakp** [comment]
Reviewed 20 of 21 files at r1.
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oscm-domainobjects/javasrc/org/oscm/domobjects/MarketplaceAccess.java, line 30 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KI7ONmKVEiohoNO7Y41:-KI7ONmKVEiohoNO7Y42:-2126841207) ([raw file](https://github.com/servicecatalog/development/blob/e497708b6e3001ff7f7303979d5df9f1a6220235/oscm-domainobjects/javasrc/org/oscm/domobjects/MarketplaceAccess.java#L30)):*
> ```Java
> @Table(uniqueConstraints = @UniqueConstraint(columnNames = { "marketplace_tkey",
>         "organization_tkey" }) )
> public class MarketplaceAccess extends DomainObjectWithEmptyDataContainer {
> ```

Class should extend DomainObjectWithoutVersioning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by badziakp** [comment]
Reviewed 4 of 11 files at r3, 10 of 26 files at r4, 4 of 5 files at r5.
Review status: 31 of 52 files reviewed at latest revision, 3 unresolved discussions.

---

*[oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceLocalBean.java, line 1077 \[r4\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KIbhACRlx7BedAIALpQ:-KIbhACRlx7BedAIALpR:-342350324) ([raw file](https://github.com/servicecatalog/development/blob/bdfae41edded522abbd6f5449da68815d922662c/oscm-marketplaceservice/javasrc/org/oscm/marketplace/bean/MarketplaceServiceLocalBean.java#L1077)):*
> ```Java
>             long orgKey) {
>         
>         String selectQuery = "SELECT m.* FROM marketplace m JOIN marketplaceaccess ma ON m.tkey = ma.marketplace_tkey WHERE m.restricted = 'true' AND ma.organization_tkey = :orgKey";
> ```

I  think NamedQuery should be used

---

*[oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java, line 63 \[r4\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KIbhpRLzOxjZKPmPP6a:-KIbhpRLzOxjZKPmPP6b:-1992354703) ([raw file](https://github.com/servicecatalog/development/blob/bdfae41edded522abbd6f5449da68815d922662c/oscm-portal/javasrc/org/oscm/ui/beans/GotoMarketplaceBean.java#L63)):*
> ```Java
>                     .getMarketplacesOwned();
> 
>             for (VOMarketplace marketplace : marketplacesOwned) {
> ```

Code is doubled: whole 'for' part can be extracted to method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by kowalczyka** [comment]
Review status: 15 of 103 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oscm-domainobjects/javasrc/org/oscm/domobjects/MarketplaceAccess.java, line 30 \[r1\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KI7ONmKVEiohoNO7Y41:-KLQu1666oXKo4TN8ads:-499146009) ([raw file](https://github.com/servicecatalog/development/blob/e497708b6e3001ff7f7303979d5df9f1a6220235/oscm-domainobjects/javasrc/org/oscm/domobjects/MarketplaceAccess.java#L30)):*
<details><summary><i>Previously, badziakp wrote…</i></summary>
> Class should extend DomainObjectWithoutVersioning
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 25 files at r8, 2 of 241 files at r9, 11 of 59 files at r10.
Review status: 29 of 103 files reviewed at latest revision, 4 unresolved discussions.

---

*[oscm-portal/javasrc/org/oscm/ui/beans/MarketplaceBean.java, line 549 \[r10\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KLQwfVta__VuQlG3z3j:-KLQwfVta__VuQlG3z3k:892145598) ([raw file](https://github.com/servicecatalog/development/blob/87c73675c0dd6b1cf8d1898f5ef317ea73c6199d/oscm-portal/javasrc/org/oscm/ui/beans/MarketplaceBean.java#L549)):*
> ```Java
>             marketplace= getMarketplaceService().getMarketplaceById(mpId);
>         } catch (ObjectNotFoundException e) {
>             //TODO    
> ```

Handle  exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 26 files at r4, 1 of 6 files at r7, 3 of 241 files at r9, 1 of 59 files at r10.
Review status: 35 of 103 files reviewed at latest revision, 5 unresolved discussions.

---

*[oscm-common/javares/ExceptionMessages_de.properties, line 365 \[r10\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KLQxMcgsZwBFx5B3JbB:-KLQxMcgsZwBFx5B3JbC:831350273) ([raw file](https://github.com/servicecatalog/development/blob/87c73675c0dd6b1cf8d1898f5ef317ea73c6199d/oscm-common/javares/ExceptionMessages_de.properties#L365)):*
> ```INI
> ex.DuplicateAdapterException=Die ID des Abrechnungssystems ist nicht eindeutig.
> ex.DuplicatePropertyKeyException=Mindestens ein Key zur Herstellung der Verbindung ist nicht eindeutig.
> ex.NonUniqueBusinessKeyException.MARKETPLACE_ACCESS=
> ```

Translations missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 10 files at r2, 4 of 26 files at r4, 1 of 1 files at r6, 1 of 6 files at r7, 8 of 25 files at r8, 9 of 241 files at r9, 27 of 59 files at r10.
Review status: 84 of 103 files reviewed at latest revision, 7 unresolved discussions.

---

*[oscm-common/javares/ExceptionMessages_ja.properties, line 367 \[r10\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KLQxcx2vlXioJ99xCOS:-KLQxcx3V2VjBxzz2sqW:831350273) ([raw file](https://github.com/servicecatalog/development/blob/87c73675c0dd6b1cf8d1898f5ef317ea73c6199d/oscm-common/javares/ExceptionMessages_ja.properties#L367)):*
> ```INI
> ex.DuplicatePropertyKeyException=\u4e00\u500b\u4ee5\u4e0a\u306e\u63a5\u7d9a\u30d7\u30ed\u30d1\u30c6\u30a3\u30ad\u30fc\u304c\u91cd\u8907\u3057\u3066\u3044\u307e\u3059\u3002
> ex.NonUniqueBusinessKeyException.MARKETPLACE_ACCESS=
> ex.LoginToClosedMarketplaceException=
> ```

Translations missing.

---

*[oscm-extsvc-internal/javasrc/org/oscm/internal/intf/ServiceProvisioningService.java, line 1391 \[r10\]](https://reviewable.io:443/reviews/servicecatalog/development/79#-KLQyo4EOLNAqa9gyqAz:-KLQyo4EOLNAqa9gyqB-:1043149247) ([raw file](https://github.com/servicecatalog/development/blob/87c73675c0dd6b1cf8d1898f5ef317ea73c6199d/oscm-extsvc-internal/javasrc/org/oscm/internal/intf/ServiceProvisioningService.java#L1391)):*
> ```Java
>      * 
>      * @return the list of customer-specific services
>      * @throws OrganizationAuthoritiesException
> ```

Wrong exception documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by kowalczyka** [comment]
Reviewed 1 of 11 files at r3, 1 of 5 files at r5, 5 of 241 files at r9, 7 of 59 files at r10, 3 of 3 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Comment by badziakp** [comment]
Reviewed 1 of 10 files at r2, 1 of 11 files at r3, 5 of 26 files at r4, 1 of 5 files at r5, 1 of 1 files at r6, 4 of 6 files at r7, 8 of 25 files at r8, 19 of 241 files at r9, 44 of 59 files at r10, 3 of 3 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/79)*

**Pull request merged**
