### PR TITLE
Updated readme file

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/development/40)

### CODE REVIEW

**Comment by badziakp** [comment]
Are you sure this is the correct version of readme.txt?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/40#-:-KFO5JttRaygfpfaTUNc:-875565920)*

**Comment by kowalczyka** [comment]
yep, this is the correct version

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/40#-:-KFO5mazMkEt4k2snV2r:1445262316)*

**Comment by badziakp** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/40#-:-KFO6A-BWPJ6Xhyns2c_:1417088721)*

**Comment by DawidCh** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servicecatalog/development/40)*

**Pull request merged**
